/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import data.CarritoVenta;
import data.Categoria;
import data.Pedido;
import data.Producto;
import data.SubCategoria;
import java.awt.TextField;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import logic.Controlador;
import logic.Paginador;
import static logic.Paginador.nextPage;
import static logic.Paginador.prevPage;

/**
 *
 * @author juanc
 */
public class OrdenVenta extends javax.swing.JFrame {

    boolean rowCreated;
    DefaultTableModel M;
    DefaultTableModel N;
    int count = 0;

    /**
     * Creates new form Usuario
     */
    public OrdenVenta() {
        initComponents();
        crearmodelo1();
        crearmodelo2();
        rowCreated = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Mostrar Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo");

        jLabel4.setText("Orden Venta");

        jButton4.setText("Generar orden Venta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(">");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setText("Carrito Compra");

        jButton7.setText("Agregar al Carrito");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton4)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(634, 634, 634)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (rowCreated) {
            for (int i = M.getRowCount() - 1; i >= 0; i--) {
                M.removeRow(i);

            }
            rowCreated = false;

        }
        Paginador.counter = 0;

        int[] nextArray = nextPage(Paginador.pilaA, Paginador.pilaB);

        Controlador.ArbolProductosTotales.printByRange(Controlador.ArbolProductosTotales.getRoot(), nextArray[0], nextArray[1]);

        Object[] elements = Paginador.currentPage;
        Object[] o = null;

        for (int i = 0; i < elements.length; i++) {
            Producto p = (Producto) elements[i];

            M.addRow(o);
            M.setValueAt(p.getCodigoProducto(), i, 2);
            M.setValueAt(p.getDescripcion(), i, 3);
            M.setValueAt(p.getPrecioVenta(), i, 4);
        }
        rowCreated = true;

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ArrayList<Producto> listaProductos = new ArrayList<>();

        Categoria categoria = new Categoria(1, "Lacteos");
        SubCategoria subCategoria = new SubCategoria(1, "yogures", categoria);

        for (int i = 0; i < jTable2.getRowCount(); i++) {
            //System.out.println(jTable2.getValueAt(i, 4).toString());
            Producto p = new Producto(Integer.parseInt(jTable2.getValueAt(i, 2).toString()),
                    jTable2.getValueAt(i, 3).toString(),
                    Integer.parseInt(jTable2.getValueAt(i, 4).toString()),
                    //TODO: valor precio compra no se esta guardando
                    0,
                    Integer.parseInt(jTable2.getValueAt(i, 1).toString()),
                    subCategoria);

            // "Seleccionar", "Cantidad", "codigo", "Descripcion", "Precio Venta"})
            //llenar array list
            listaProductos.add(p);
        }
        CarritoVenta venta = new CarritoVenta(listaProductos);
                    //Controlador.CarritoDeVentas.enqueue(venta);
        System.out.println("Venta Encolada!");
        System.out.println("Codigo Venta: " + venta.getCodigoVenta());
        

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (rowCreated) {
            for (int i = M.getRowCount() - 1; i >= 0; i--) {
                M.removeRow(i);

            }
            rowCreated = false;
        }

        if (cod.getText() == null) {
            //TODO:  REPARAR VALIDACION SE ESTA USANDO ESTA CONDICIONAL
            System.out.println("No hay elemento a buscar");

        } else {

            int codigoProducto = Integer.parseInt(cod.getText());
            Producto p = new Producto(codigoProducto, null, 0, 0, 0, null);

            //Object[] elements = new Object[1];
            Producto temp = (Producto) Controlador.ArbolProductosTotales.find(Controlador.ArbolProductosTotales.getRoot(), p).getKey();
            //elements[0] = temp;
            Object[] o = null;

            M.addRow(o);
            M.setValueAt(temp.getCodigoProducto(), 0, 2);
            M.setValueAt(temp.getDescripcion(), 0, 3);
            M.setValueAt(temp.getPrecioVenta(), 0, 4);

            addCheckBox(0, 1, jTable1);
            rowCreated = true;
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Paginador.vaciarPilas();
        Paginador.cargarPilas();

        if (rowCreated) {
            for (int i = M.getRowCount() - 1; i >= 0; i--) {
                M.removeRow(i);

            }
            rowCreated = false;

        }
        Paginador.counter = 0;
        int[] nextArray = nextPage(Paginador.pilaA, Paginador.pilaB);

        Controlador.ArbolProductosTotales.printByRange(Controlador.ArbolProductosTotales.getRoot(), nextArray[0], nextArray[1]);

        Object[] elements = Paginador.currentPage;
        Object[] o = null;

        for (int i = 0; i < elements.length; i++) {

            Producto p = (Producto) elements[i];

            M.addRow(o);
            M.setValueAt(p.getCodigoProducto(), i, 2);
            M.setValueAt(p.getDescripcion(), i, 3);
            M.setValueAt(p.getPrecioVenta(), i, 4);
            // "Seleccionar", "Cantidad", "codigo", "Descripcion", "Precio Venta"})
        }
        addCheckBox(0, 1, jTable1); //repair
        rowCreated = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (rowCreated) {
            for (int i = M.getRowCount() - 1; i >= 0; i--) {
                M.removeRow(i);

            }
            rowCreated = false;

        }
        Paginador.counter = 0;

        int[] prevArray = prevPage(Paginador.pilaA, Paginador.pilaB);

        Controlador.ArbolProductosTotales.printByRange(Controlador.ArbolProductosTotales.getRoot(), prevArray[0], prevArray[1]);

        Object[] elements = Paginador.currentPage;
        Object[] o = null;

        for (int i = 0; i < elements.length; i++) {
            Producto p = (Producto) elements[i];

            M.addRow(o);
            M.setValueAt(p.getCodigoProducto(), i, 2);
            M.setValueAt(p.getDescripcion(), i, 3);
            M.setValueAt(p.getPrecioVenta(), i, 4);

        }
        rowCreated = true;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        for (int i = 0; i < jTable1.getRowCount(); i++) {

            if (IsSelected(i, 0, jTable1)) {

                Object[] o = null;
                N.addRow(o);

                N.setValueAt(jTable1.getValueAt(i, 1), count, 1);
                N.setValueAt(jTable1.getValueAt(i, 2), count, 2);
                N.setValueAt(jTable1.getValueAt(i, 3), count, 3);
                N.setValueAt(jTable1.getValueAt(i, 4), count, 4);
                count++;

                addCheckBox(0, 1, jTable2);
                jTable1.setValueAt(null, i, 0);
            }
        }


    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new OrdenVenta().setVisible(true);
            }
        });
    }

    private void crearmodelo1() {
        try {
            M = (new DefaultTableModel(null, new String[]{
                "Seleccionar", "Cantidad", "codigo", "Descripcion", "Precio Venta"}) {
            });
            jTable1.setModel(M);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }

    private void crearmodelo2() {
        try {
            N = (new DefaultTableModel(null, new String[]{
                "Seleccionar", "Cantidad", "codigo", "Descripcion", "Precio Venta"}) {
            });
            jTable2.setModel(N);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }

    /* public DefaultTableModel mostrarDatos(){
    this.validate();
crearmodelo();
Object o[]=null;

   
Datos = registro.GetDatos();
ArrayList<Usuario> usuariosBusqueda = new ArrayList<Usuario>();

for(int i=0;i<Datos.size ();i++){
    Usuario c= (Usuario) Datos.get(i);
    if(c.getCategoria().equals((String) busc.getSelectedItem()))
    {
        if(c.getCiudad().equals((String) jComboBox1.getSelectedItem()))
        {
            if(c.getDescripcion().contains((String) jTextField1.getText()))
            {
                usuariosBusqueda.add(c);
            }
        }
    }
}

for(int i=0;i<usuariosBusqueda.size ();i++){
    Usuario c= (Usuario) usuariosBusqueda.get(i);
    M.addRow(o); 
    M.setValueAt(c.getNombres(),i,2);
    M.setValueAt(c.getApellidos(),i,3);
    M.setValueAt(c.getSexo(),i,4);
    M.setValueAt(c.getCedula(),i,5);
    M.setValueAt(c.getCiudad(),i,6);
    M.setValueAt(c.getCategoria(),i,7);
    M.setValueAt(c.getCelular(),i,8);
    M.setValueAt(c.getDescripcion(),i,9);
}
return M;
    }*/
    public void addCheckBox(int column, int column1, JTable table) {
        TableColumn tc = table.getColumnModel().getColumn(column);
        TableColumn tr = table.getColumnModel().getColumn(column1);
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
        tr.setCellEditor(table.getDefaultEditor(TextField.class));
        tr.setCellRenderer(table.getDefaultRenderer(TextField.class));

    }

    public Boolean IsSelected(int row, int colum, JTable table) {
        return table.getValueAt(row, colum) != null;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
