/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import data.CarritoVenta;
import data.Producto;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logic.Controlador;

/**
 *
 * @author juanc
 */
public class RealizarVenta extends javax.swing.JFrame {

    boolean rowCreated;

    /**
     * Creates new form Usuario
     */
    public RealizarVenta() {
        initComponents();
        crearmodelo();
        rowCreated = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(61, 181, 188));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recepción venta");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Orden ");

        jButton2.setBackground(new java.awt.Color(248, 215, 31));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton2.setText("Realizar venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(248, 215, 31));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(248, 215, 31));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton1.setText("Siguiente venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/venta_2.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Storapp Logo 1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(30, 30, 30)
                                    .addComponent(jButton2)
                                    .addGap(31, 31, 31)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Usuario user = new Usuario();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        
        java.net.URL url = ClassLoader.getSystemResource("imagenes/icon.png");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(url);
        user.setIconImage(img);
        
        this.dispose();        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (rowCreated) {
            for (int i = M.getRowCount() - 1; i >= 0; i--) {
                M.removeRow(i);

            }
            rowCreated = false;

        }

        if (!Controlador.ColaDeVentas.isEmpty()) {

            
            //CALCULAR A DE TIEMPO EJECUCION
                    long TInicio3,
                     TFin3,
                     tiempo3;
                    TInicio3 = System.currentTimeMillis();
                    //inicio algoritmo
                       CarritoVenta venta = Controlador.ColaDeVentas.getFront();
                    //fin algoritmo
                    TFin3 = System.currentTimeMillis();
                    tiempo3 = TFin3 - TInicio3;
                    System.out.println("Tiempo ms LinkedQueue<CarritoCompra> | op: getFront() " + tiempo3);
                //FIN DE LA CALCULADORA
            
            
            

            for (int i = 0; i < venta.getListaProductos().size(); i++) {
                Object o[] = null;
                Producto p = (Producto) venta.getListaProductos().get(i);
                M.addRow(o);
                M.setValueAt(p.getCodigoProducto(), i, 0);
                M.setValueAt(p.getDescripcion(), i, 1);
                M.setValueAt(p.getPrecioVenta(), i, 2);
                M.setValueAt(p.getCantidadUnidades(), i, 3);
                // "codigo","Descripcion","Precio Venta","Cantidad"}){});
            }
            rowCreated = true;
        } else {
            System.out.println("No hay ventas pendientes");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (M.getRowCount() > 0) {
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                Producto p = new Producto(Integer.parseInt(jTable1.getValueAt(i, 0).toString()),
                        jTable1.getValueAt(i, 1).toString(),
                        Integer.parseInt(jTable1.getValueAt(i, 2).toString()),
                        0,
                        Integer.parseInt(jTable1.getValueAt(i, 3).toString()),
                        null);

                //aumentar stock
                //Controlador.ArbolProductosTotales.insert(Controlador.ArbolProductosTotales.getRoot(), p);
                Producto actual = (Producto) Controlador.ArbolProductosTotales.find(Controlador.ArbolProductosTotales.getRoot(), p).getKey();

                actual.reducirStock(p);
                System.out.println("stock reducido");

                Controlador.ArbolProductosTotales.find(Controlador.ArbolProductosTotales.getRoot(), p).setKey(actual);

            }

            //crear historial de ventas, mover el pedido a lista de historial
            System.out.println("Venta realizada!");
            System.out.println("Stock Actualizado!");
            
            
            
            
             //CALCULAR A DE TIEMPO EJECUCION
                    long TInicio3,
                     TFin3,
                     tiempo3;
                    TInicio3 = System.currentTimeMillis();
                    //inicio algoritmo
                       CarritoVenta venta = Controlador.ColaDeVentas.dequeue();
                    //fin algoritmo
                    TFin3 = System.currentTimeMillis();
                    tiempo3 = TFin3 - TInicio3;
                    System.out.println("Tiempo ms LinkedQueue<CarritoCompra> | op: dequeue() " + tiempo3);
                //FIN DE LA CALCULADORA
        
            
            
            
            
            
            
            
            
            System.out.println("Venta Noº: " + venta.getCodigoVenta() + " Realizada!");

            for (int i = M.getRowCount() - 1; i >= 0; i--) {
                M.removeRow(i);

            }
            rowCreated = false;

        }else{
            System.out.println("No hay venta seleccionada");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new RealizarVenta().setVisible(true);
            }
        });
    }
    DefaultTableModel M;

    private void crearmodelo() {
        try {
            M = (new DefaultTableModel(null, new String[]{
                "codigo", "Descripcion", "Precio Venta", "Cantidad"}) {
            });
            jTable1.setModel(M);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }
    /* public DefaultTableModel mostrarDatos(){
    this.validate();
crearmodelo();
Object o[]=null;

   
Datos = registro.GetDatos();
ArrayList<Usuario> usuariosBusqueda = new ArrayList<Usuario>();

for(int i=0;i<Datos.size ();i++){
    Usuario c= (Usuario) Datos.get(i);
    if(c.getCategoria().equals((String) busc.getSelectedItem()))
    {
        if(c.getCiudad().equals((String) jComboBox1.getSelectedItem()))
        {
            if(c.getDescripcion().contains((String) jTextField1.getText()))
            {
                usuariosBusqueda.add(c);
            }
        }
    }
}

for(int i=0;i<usuariosBusqueda.size ();i++){
    Usuario c= (Usuario) usuariosBusqueda.get(i);
    M.addRow(o); 
    M.setValueAt(c.getNombres(),i,2);
    M.setValueAt(c.getApellidos(),i,3);
    M.setValueAt(c.getSexo(),i,4);
    M.setValueAt(c.getCedula(),i,5);
    M.setValueAt(c.getCiudad(),i,6);
    M.setValueAt(c.getCategoria(),i,7);
    M.setValueAt(c.getCelular(),i,8);
    M.setValueAt(c.getDescripcion(),i,9);
}
return M;
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
